version: '3'

volumes:
  wordpress_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/rmazurit/data/wordpress

  database_volume:
    driver_opts:
      o: bind
      type: none
      device: /home/rmazurit/data/mariadb

networks:
    inception:
        driver: bridge

services:

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_ROOT: ${DB_ROOT}
      DB_PASS: ${DB_PASS}
      WP_URL: ${WP_URL}
      WP_BLOG_TITLE: ${WP_BLOG_TITLE}
      WP_ROOT_USER: ${WP_ROOT_USER}
      WP_ROOT_PASSWORD: ${WP_ROOT_PASSWORD}
      WP_ROOT_MAIL: ${WP_ROOT_MAIL}
      WP_USER: ${WP_USER}
      WP_USER_MAIL: ${WP_USER_MAIL}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/
    networks:
      - inception
    restart: unless-stopped

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www/
    networks:
      - inception
    restart: unless-stopped
